#!/bin/bash
echo "ENTER THE USERNAME"
read p
echo "Enter the passwordcomplex"
read -s  pa
for ((i=0;i<=5;i++))
do
useradd $p$i
echo "Below are details of user $p$i"
grep "$p$i" /etc/passwd
echo "$p$pa" |passwd "$p$i" --stdin
echo "Below are details to verofy passwotrd set or not"
grep "$p$i" /etc/shadow
echo "==============================================="
done
