#!/bin/bash
for i in "dhanraj" "pavanraj" "megharaj" "nagaraj" "kiran" "vinay" "thejaswini"
do
col=$(grep $i /etc/passwd |wc -l)
if [[ $col -gt 0 ]]
then
echo -e "User $i is present in server\nBelow are the details of user $i"
grep $i /etc/passwd
coc=$(grep "$i" /etc/shadow |cut -d ":" -f2|wc -c)
if [[ $coc -gt 3 ]]
then
echo "Password already set for user $i"
grep $i /etc/shadow
else
echo "Password Not user for user $i"
grep $i /etc/shadow
echo "Enter '1' to set password"
read opt
if [[ $opt -eq 1 ]]
then
echo "User $i confirmed to set password"
echo $i |passwd $i --stdin
echo "Password has been set successfully for user $i"
grep $i /etc/shadow
else
echo "User $i not confirmed to set password"
fi
fi
else
echo "User $i is not present in server"
useradd $i
echo $i | passwd $i --stdin
fi
echo "=========================================="
done
